export type ComponentColor = 'primary' | 'secondary' | 'accent'
export type ComponentShape = 'circle' | 'square'
export type ComponentSize = 'lg' | 'md' | 'sm' | 'xs'
export type ComponentStatus = 'info' | 'success' | 'warning' | 'error'
export type ComponentVariant = 'outline' | 'text' | 'link'